version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: redmine-db
    restart: always
    environment:
      MYSQL_DATABASE: redmine_db
      MYSQL_USER: redmine
      MYSQL_PASSWORD: xunjmq84
      MYSQL_ROOT_PASSWORD: Xunjmq84!
    volumes:
      - mysql_data:/var/lib/mysql

  redmine:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: redmine-app
    restart: always
    depends_on:
      - db
    environment:
      BUNDLE_FORCE_RUBY_PLATFORM: true
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PORT: 3306
      REDMINE_DB_DATABASE: redmine_db
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: xunjmq84
      RAILS_SECRET_KEY_BASE: "a48309b38e8c96802542047f786b0e6bce7cb89905159f7e468d3904476d25c8692c3c68ec36b18f498d7d4758c3bdc7857ef7bb5c3e7cb5d91f3ab8d9ea2553"
    volumes:
      - redmine_data:/usr/src/redmine/files
      - ./config/database.yml:/usr/src/redmine/config/database.yml
      - ./plugins:/usr/src/redmine/plugins
      - ./themes:/usr/src/redmine/public/themes
      - ./redmine-init.sh:/usr/local/bin/redmine-init.sh
    entrypoint: ["/usr/local/bin/redmine-init.sh"]
    command: ["rails", "server", "-b", "0.0.0.0"]

  nginx:
    image: nginx:latest
    container_name: redmine-nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - redmine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  mysql_data:
  redmine_data:
