FROM ghcr.io/silverbulletmd/silverbullet:latest

# Copy AI plugin
#COPY silverbullet/PLUGINS/silverbullet-ai /space/PLUGINS/silverbullet-ai

# Copy configs
#COPY silverbullet/SETTINGS /space/SETTINGS
#COPY silverbullet/SECRETS /space/SECRETS
